
## ----------- Loading in Observed Data (MDS.combined 2UMI) ----------- ##

```{r}
alt3p_findings_2UMI <- read.table("/gpfs/commons/groups/landau_lab/SF3B1_splice_project/7.Permutation_junction_output/6.Comb_patients_2WT/5_read_threshold/MDS_P5_P6/logOR_within_cell_type_ALT_3P_Junctions_with_threshold_info.txt")
alt3p_findings <- alt3p_findings_2UMI

Obs <- alt3p_findings
Obs$gene <- paste(Obs$gene)
Obs$cryptic.junction <- paste0(Obs$chr,":",Obs$three_prime)
```


## ----------- Loading in Reference Data (Pellagati et al Junctions) and converting into proper format (with hg38 coordinates)  ----------- ##

```{r}
pellagati.reference <-read_csv("/gpfs/commons/groups/landau_lab/SF3B1_splice_project/11.Alt3p_splicing_references/Pallegatti_Suppl3_SF3B1.csv")
pellagati.reference.a3ss <- pellagati.reference[which(pellagati.reference$`Event type` == "A3SS"),]

junctions.hg38 <- read.table("/gpfs/commons/groups/landau_lab/SF3B1_splice_project/11.Alt3p_splicing_references/junctions.hg38.pellagati.txt")

pellagati.reference.a3ss$hg38 <- paste0(junctions.hg38$V1)
pellagati.reference.a3ss$start.hg38 <- unlist(lapply(strsplit(pellagati.reference.a3ss$hg38, split= "-"), "[",1))
pellagati.reference.a3ss$start.hg38 <- unlist(lapply(strsplit(pellagati.reference.a3ss$start.hg38, split= ":"), "[",2))
pellagati.reference.a3ss$end.hg38 <- unlist(lapply(strsplit(pellagati.reference.a3ss$hg38,split= "-"), "[",2))

junctions.hg38
pellagati.reference.a3ss

Ref <- pellagati.reference.a3ss[which(pellagati.reference.a3ss$Gene %in% intersect(Obs$gene, pellagati.reference.a3ss$Gene)),] %>% arrange(Gene)
Ref <- pellagati.reference.a3ss

##Add in fiveprime and threeprim like we have 
Ref = Ref %>% mutate(five_prime = ifelse(Strand=="+", start.hg38, end.hg38),
                     three_prime = ifelse(Strand=="+", end.hg38, start.hg38))

Ref$cryptic.junction <- paste0("chr",Ref$Chr,":",Ref$five_prime)
Ref$dPSI <- (Ref$`Inclusion Level_WTMDS` * 100)
```


## ----------- Fnalizing tables  ----------- ##

#Remove instances where there are multiple junctions using the same cryptic site (i.e. different 5p ends)

```{r}
##Final tables
Ref.final <- Ref[which(Ref$cryptic.junction %in% intersect(Ref$cryptic.junction,Obs$cryptic.junction)),] %>% arrange(cryptic.junction)
Obs.final <- Obs[which(Obs$cryptic.junction %in% intersect(Ref$cryptic.junction,Obs$cryptic.junction)),] %>% arrange(cryptic.junction)

Ref.final
Obs.final

Ref.final <- Ref.final[which(!(Ref.final$Gene %in% c("TMEM91") )),]
Obs.final <- Obs.final[which(!(Obs.final$gene %in% c("TMEM91") )),]

Obs.final <- Obs.final[which(!(Obs.final$five_prime_ID %in% c("clu_86720","clu_82654","clu_68133","clu_68132","clu_47488","clu_35713","clu_23648","clu_17093","clu_17091"))),]

Ref.final
Obs.final

gene.list <- Obs.final$gene
```

##Create Table to plot
```{r}
ref.vs.obs.junc.dPSI.comparison <- as.data.frame(matrix(ncol=2,nrow=length(gene.list)))

colnames(ref.vs.obs.junc.dPSI.comparison) <- c("Ref","Obs")
rownames(ref.vs.obs.junc.dPSI.comparison)<- gene.list

ref.vs.obs.junc.dPSI.comparison$Ref <- Ref.final$dPSI
ref.vs.obs.junc.dPSI.comparison$Obs <- Obs.final$dPSI

ggscatter(ref.vs.obs.junc.dPSI.comparison, x = "Ref", y = "Obs", add = "reg.line", add.params = list(color = "blue"), conf.int = FALSE, xlab = paste("Reference dPSIs"), ylab = paste0("Observed dPSIs"), label = rownames(ref.vs.obs.junc.dPSI.comparison), repel = TRUE) + stat_cor(label.x = -15, label.y = 50) + stat_cor(method = "spearman", cor.coef.name = "rho",label.x = -15, label.y = 45)

```

