

##Looking at the ovelap betten CH and MDS 
```{r}
ch.hspc <- read.table("/gpfs/commons/groups/landau_lab/SF3B1_splice_project/7.Permutation_junction_output/5.Comb_patients_ind_celltype_merge_counts/CH_combined/HSPC/logOR_within_cell_type_ONLY_CRYPTIC_3P_Junctions_with_threshold_info.txt")

mds.hspc <- read.table("/gpfs/commons/groups/landau_lab/SF3B1_splice_project/7.Permutation_junction_output/7.Comb_patients_ind_celltype_merge_counts_2WT/MDS_P5_P6/HSPC/logOR_within_cell_type_ONLY_CRYPTIC_3P_Junctions_with_threshold_info.txt")

ch.ep <- read.table("/gpfs/commons/groups/landau_lab/SF3B1_splice_project/7.Permutation_junction_output/5.Comb_patients_ind_celltype_merge_counts/CH_combined/EP/logOR_within_cell_type_ONLY_CRYPTIC_3P_Junctions_with_threshold_info.txt")

mds.ep <- read.table("/gpfs/commons/groups/landau_lab/SF3B1_splice_project/7.Permutation_junction_output/7.Comb_patients_ind_celltype_merge_counts_2WT/MDS_P5_P6/EP/logOR_within_cell_type_ONLY_CRYPTIC_3P_Junctions_with_threshold_info.txt")



ch.bulk <- read.table("/gpfs/commons/groups/landau_lab/SF3B1_splice_project/7.Permutation_junction_output/4.Comb_patients_merge_counts/CH_combined/logOR_within_cell_type_ONLY_CRYPTIC_3P_Junctions_with_threshold_info.txt")
mds.bulk <- read.table("/gpfs/commons/groups/landau_lab/SF3B1_splice_project/7.Permutation_junction_output/6.Comb_patients_2WT/5_read_threshold/MDS_P5_P6/logOR_within_cell_type_ONLY_CRYPTIC_3P_Junctions_with_threshold_info.txt")

```



```{r}
dPSI.val <- 1

ch.hspc.sig.junc <- ch.hspc[which(ch.hspc$pvalue <= 0.05 & ch.hspc$dPSI >= dPSI.val),]$intron_junction
mds.hspc.sig.junc <- mds.hspc[which(mds.hspc$pvalue <= 0.05 & mds.hspc$dPSI >= dPSI.val),]$intron_junction


joint.events <- intersect(ch.hspc.sig.junc, mds.hspc.sig.junc)
joint.events
ch.hspc[which(ch.hspc$intron_junction %in% joint.events),]
joint.events.hspc <- intersect(ch.hspc.sig.junc, mds.hspc.sig.junc)


ch.ep.sig.junc <- ch.ep[which(ch.ep$pvalue <= 0.05 & ch.ep$dPSI >= dPSI.val),]$intron_junction
mds.ep.sig.junc <- mds.ep[which(mds.ep$pvalue <= 0.05 & mds.ep$dPSI >= dPSI.val),]$intron_junction
joint.events.ep <- intersect(ch.ep.sig.junc, mds.ep.sig.junc)


ch.hspc[which(ch.hspc$intron_junction %in% joint.events.hspc),]
ch.ep[which(ch.ep$intron_junction %in% joint.events.ep),]
```



##Correlate the dPSI values and if they are going in the same direction
```{r fig.height=10, fig.width=10}
#HSPC
rownames(ch.hspc) <- ch.hspc$intron_junction
rownames(mds.hspc) <- mds.hspc$intron_junction

shared.junctions <- intersect(ch.hspc$intron_junction, mds.hspc$intron_junction)
nrow(ch.hspc)
nrow(mds.hspc)
length(shared.junctions)
for.scatter
for.scatter <- as.data.frame(cbind(ch.hspc[shared.junctions,]$dPSI, mds.hspc[shared.junctions,]$dPSI))
for.scatter

colnames(for.scatter) <- c("ch.dpsi","mds.dpsi")
rownames(for.scatter) <- rownames(ch.hspc[shared.junctions,])

for.scatter$gene <- ch.hspc[shared.junctions,]$gene
for.scatter$sig.both <- 0
for.scatter$sig.mds <- 0
for.scatter$sig.ch <- 0


ch.sig <- rownames(ch.hspc[which(ch.hspc$pvalue <= 0.05),])
mds.sig <- rownames(mds.hspc[which(mds.hspc$pvalue <= 0.05),])

length(ch.sig)
length(mds.sig)

for.scatter[which(rownames(for.scatter) %in% ch.sig ), ]$sig.ch <- 1
for.scatter[which(rownames(for.scatter) %in% mds.sig), ]$sig.mds <- 1
for.scatter[which(for.scatter$sig.mds ==1 & for.scatter$sig.ch ==1),]$sig.both <- 1

library(ggrepel)
ggplot(for.scatter, aes(x=ch.dpsi, y=mds.dpsi)) + geom_point(size=1) +
  geom_point(data=for.scatter[which(for.scatter$sig.both ==1),], aes(x=ch.dpsi, y=mds.dpsi), colour="red", size=2) + 
  geom_hline(yintercept=0) + 
  geom_vline(xintercept=0) + 
  geom_text_repel(data=for.scatter[which(for.scatter$sig.both ==1),], aes(x=ch.dpsi, y=mds.dpsi, label=gene))

ggplot(for.scatter, aes(x=ch.dpsi, y=mds.dpsi)) + geom_point(size=1) +
  geom_point(data=for.scatter[which(for.scatter$sig.mds ==1),], aes(x=ch.dpsi, y=mds.dpsi), colour="blue", size=2) + 
  geom_hline(yintercept=0, linetype = "dotted") + 
  geom_text_repel(data=for.scatter[which(for.scatter$sig.mds ==1),], aes(x=ch.dpsi, y=mds.dpsi, label=gene))

ggplot(for.scatter, aes(x=ch.dpsi, y=mds.dpsi)) + geom_point(size=1) +
  geom_point(data=for.scatter[which(for.scatter$sig.ch ==1),], aes(x=ch.dpsi, y=mds.dpsi), colour="green", size=2) + 
  geom_vline(xintercept=0, linetype = "dotted") + 
  geom_text_repel(data=for.scatter[which(for.scatter$sig.ch ==1),], aes(x=ch.dpsi, y=mds.dpsi, label=gene))

```




```{r fig.height=10, fig.width=10}
#EP
rownames(ch.ep) <- ch.ep$intron_junction
rownames(mds.ep) <- mds.ep$intron_junction

shared.junctions <- intersect(ch.ep$intron_junction, mds.ep$intron_junction)
ch.ep.sub <- ch.ep[which(ch.ep$intron_junction %in% shared.junctions), ]
mds.ep.sub <- mds.ep[which(mds.ep$intron_junction %in% shared.junctions), ]

rownames(ch.ep.sub) <- ch.ep.sub$intron_junction
rownames(mds.ep.sub) <- mds.ep.sub$intron_junction

mds.ep.sub
ch.ep.sub
length(shared.junctions)

for.scatter <- as.data.frame(cbind(ch.ep.sub[shared.junctions,]$dPSI, mds.ep.sub[shared.junctions,]$dPSI))

colnames(for.scatter) <- c("ch.dpsi","mds.dpsi")
rownames(for.scatter) <- rownames(ch.ep.sub[shared.junctions,])
for.scatter$gene <- ch.ep.sub[shared.junctions,]$gene
for.scatter$sig.both <- 0
for.scatter$sig.mds <- 0
for.scatter$sig.ch <- 0

ch.sig <- rownames(ch.ep.sub[which(ch.ep.sub$pvalue <= 0.05),])
mds.sig <- rownames(mds.ep.sub[which(mds.ep.sub$pvalue <= 0.05),])

for.scatter[ch.sig, ]$sig.ch <- 1
for.scatter[mds.sig, ]$sig.mds <- 1
for.scatter[which(for.scatter$sig.mds ==1 & for.scatter$sig.ch ==1),]$sig.both <- 1


ggplot(for.scatter, aes(x=ch.dpsi, y=mds.dpsi)) + geom_point(size=1) +
  geom_point(data=for.scatter[which(for.scatter$sig.both ==1),], aes(x=ch.dpsi, y=mds.dpsi), colour="red", size=2) + 
  geom_hline(yintercept=0) + 
  geom_vline(xintercept=0) + 
  geom_text_repel(data=for.scatter[which(for.scatter$sig.both ==1),], aes(x=ch.dpsi, y=mds.dpsi, label=gene))

ggplot(for.scatter, aes(x=ch.dpsi, y=mds.dpsi)) + geom_point(size=1) +
  geom_point(data=for.scatter[which(for.scatter$sig.mds ==1),], aes(x=ch.dpsi, y=mds.dpsi), colour="blue", size=2) + 
  geom_hline(yintercept=0, linetype = "dotted") + 
  geom_text_repel(data=for.scatter[which(for.scatter$sig.mds ==1),], aes(x=ch.dpsi, y=mds.dpsi, label=gene))

ggplot(for.scatter, aes(x=ch.dpsi, y=mds.dpsi)) + geom_point(size=1) +
  geom_point(data=for.scatter[which(for.scatter$sig.ch ==1),], aes(x=ch.dpsi, y=mds.dpsi), colour="green", size=2) + 
  geom_vline(xintercept=0, linetype = "dotted") + 
  geom_text_repel(data=for.scatter[which(for.scatter$sig.ch ==1),], aes(x=ch.dpsi, y=mds.dpsi, label=gene))


```


##Compare the mut PSI's instead of dPSI (given the differences in VAF!)

```{r}
ch.bulk.sub
mds.bulk.sub
```


```{r}

coverage <- 10

ch.bulk.sub <- ch.bulk[which(ch.bulk$three.mut.cluster.cov >= coverage),]
mds.bulk.sub <- mds.bulk[which(mds.bulk$three.mut.cluster.cov >=coverage),]

rownames(ch.bulk.sub) <- ch.bulk.sub$intron_junction
mds.bulk.sub <- mds.bulk.sub[!(row.names(mds.bulk.sub) %in% c("2700")),]
rownames(mds.bulk.sub) <- mds.bulk.sub$intron_junction

shared.junctions <- intersect(ch.bulk.sub$intron_junction, mds.bulk.sub$intron_junction)

for.scatter <- as.data.frame(cbind(ch.bulk.sub[shared.junctions,]$mut.psi, mds.bulk.sub[shared.junctions,]$mut.psi))
rownames(for.scatter) <- shared.junctions
colnames(for.scatter) <- c("ch.mut.psi","mds.mut.psi")
for.scatter

ggplot(for.scatter, aes(x=ch.mut.psi, y=mds.mut.psi)) + geom_point(size=1) 

cor.test(for.scatter$ch.mut.psi, for.scatter$mds.mut.psi)


ch.bulk.sub <- ch.bulk[which(ch.bulk$three.wt.cluster.cov >= coverage),]
mds.bulk.sub <- mds.bulk[which(mds.bulk$three.wt.cluster.cov >=coverage),]
rownames(ch.bulk.sub) <- ch.bulk.sub$intron_junction
mds.bulk.sub <- mds.bulk.sub[!(row.names(mds.bulk.sub) %in% c("2700")),]
rownames(mds.bulk.sub) <- mds.bulk.sub$intron_junction
shared.junctions <- intersect(ch.bulk.sub$intron_junction, mds.bulk.sub$intron_junction)

for.scatter <- as.data.frame(cbind(ch.bulk.sub[shared.junctions,]$wt.psi, mds.bulk.sub[shared.junctions,]$wt.psi))
rownames(for.scatter) <- shared.junctions
colnames(for.scatter) <- c("ch.wt.psi","mds.wt.psi")
for.scatter

ggplot(for.scatter, aes(x=ch.wt.psi, y=mds.wt.psi)) + geom_point(size=1)

cor.test(for.scatter$ch.wt.psi, for.scatter$mds.wt.psi)


```


##Compare the full bulk PSI's to show that we are detecting these in CH but not as great of a magnitude as in MDS
```{r}

```

