##Addind in Column with clusterIDs that are grouped by 3p sites instead of 5p sites - to start looking into alternative 5p splicing signal


##load in full junction meta matrix 
```{r}
load("/gpfs/commons/groups/landau_lab/SF3B1_splice_project/6.Junction_analysis_files/1.ONT_juncs/p1_v2_align_smartseq_nofilter_gtf_basic_all.introns.info.Rdata")


colnames(all_introns_meta)[4] <- "clusterID_alt3p"
all_introns_meta$clusterID_alt5p <- NA
all_introns_meta <- add_column(all_introns_meta, all_introns_meta$clusterID_alt5p, .before=5)
all_introns_meta$clusterID_alt5p <- NULL
colnames(all_introns_meta)[5] <- "clusterID_alt5p"
all_introns_meta
```



```{r}
all_introns_meta = all_introns_meta %>% mutate(five_prime = ifelse(strand=="+", start, end),
                                               three_prime = ifelse(strand=="+", end, start))

all_introns_meta
print("hi")
```


##Code for 3p clusterIDs
```{r}
#3p  prime groups
#fivep_groups = all_introns_meta %>% group_indices(chr, five_prime)
#all_introns_meta$clusterID_alt3p <- fivep_groups
```

##Code for 5p clusterIDs
```{r}
#Five prime groups
threep_groups = all_introns_meta %>% group_indices(chr, three_prime)
all_introns_meta$clusterID_alt5p <- paste("clu_" , threep_groups, sep="")

all_introns_meta[,c("chr","start","end","strand","clusterID_alt3p","clusterID_alt5p","five_prime","three_prime")] %>% arrange(three_prime)
all_introns_meta[,c("chr","start","end","strand","clusterID_alt3p","clusterID_alt5p","five_prime","three_prime")] %>% arrange(five_prime)
all_introns_meta
```



```{r}
counts_matrix <- read.table("/gpfs/commons/groups/landau_lab/SF3B1_splice_project/6.Junction_analysis_files/Alt5p_clusters/p1_align_smartseq_nofilter_perind_numers.counts.txt")

counts_matrix <- add_column(counts_matrix, all_introns_meta$clusterID_alt5p , .before=1)
counts_matrix <- add_column(counts_matrix, rownames(counts_matrix) , .before=1)

colnames(counts_matrix)[1] <- "rownames"
#counts_matrix$`all_introns_meta$clusterID_alt5p` <- all_introns_meta$clusterID_alt5p
counts_matrix$rownames <- unlist(lapply(strsplit(rownames(counts_matrix),split= ":clu"), "[",1))
counts_matrix$rownames <- paste(counts_matrix$rownames, ":",counts_matrix$`all_introns_meta$clusterID_alt5p`, sep="")
counts_matrix
rownames(counts_matrix) <- counts_matrix$rownames

```


```{r}
counts_matrix[which(counts_matrix$rownames == "chr1:112694172:112694452:clu_9017"),]


length(rownames(counts_matrix))
length(unique(counts_matrix$`all_introns_meta$clusterID_alt5p`))
```


```{r}
gene <- "ITGB1"
all_introns_meta[which(all_introns_meta$gene == gene) ,c("chr","start","end","gene","strand","clusterID_alt3p","clusterID_alt5p","five_prime","three_prime")] %>% arrange(three_prime)

all_introns_meta[which(all_introns_meta$gene == gene),c("chr","start","end","gene","strand","clusterID_alt3p","clusterID_alt5p","five_prime","three_prime")] %>% arrange(five_prime)
```

```{r}
all_introns_meta[which(all_introns_meta$verdict =="cryptic_fiveprime"),]
```


```{r}

all_introns_meta[which(all_introns_meta$gene =="KIF5B"),]
```

##Save Matrix:
```{r}
save(all_introns_meta, file="/gpfs/commons/groups/landau_lab/SF3B1_splice_project/6.Junction_analysis_files/Alt5p_clusters/p1_v2_align_smartseq_nofilter_gtf_basic.5p_and_3p_clu.all.introns.info.Rdata")
```


##Fix the count matrix as well
```{r}

```

